# Generated by Django 6.0.7 on 2026-07-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='image_base64',
            field=models.TextField(blank=True, help_text='String da imagem em Base64', null=True),
        ),
    ]
