# Generated by Django 6.0.7 on 2026-07-25 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_gift_description_gift_image_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='payment_proof_file',
            field=models.FileField(blank=True, null=True, upload_to='gift_proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='gift',
            name='payment_proof_type',
            field=models.CharField(blank=True, choices=[('PIX', 'Comprovante Pix'), ('PURCHASE', 'Comprovante de Compra')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='category',
            field=models.CharField(choices=[('CASA', 'Casa'), ('CRIATIVO', 'Criativo')], max_length=100),
        ),
    ]
