# Generated by Django 6.0.7 on 2026-07-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_gift_buyer_email_gift_payment_proof_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]