# Generated by Django 6.0.7 on 2026-08-01 17:27

from django.db import migrations, models


def ensure_gift_table(apps, schema_editor):
    Gift = apps.get_model('registry', 'Gift')
    table_name = Gift._meta.db_table

    if table_name not in schema_editor.connection.introspection.table_names():
        schema_editor.create_model(Gift)


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_gift_link'),
    ]

    operations = [
        migrations.RunPython(ensure_gift_table, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='gift',
            name='image_base64',
        ),
        migrations.AddField(
            model_name='gift',
            name='image',
            field=models.ImageField(blank=True, help_text='Faça o upload da imagem do presente', null=True, upload_to='gifts/images/'),
        ),
        migrations.AddField(
            model_name='gift',
            name='link2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='link3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='link4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
