# Generated by Django 6.0.7 on 2026-07-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='name_companions',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
